### ISSUE TITLE
Temporal constraints and location restrictions

### ISSUE THREAD

**Issue by samuelgoto** [samuelgoto/arpub#1]
How should we deal with artifacts that are only applicable within a certain time frame? Or within location restriction? Should these be **composite landmarks**? Or are they intrinsically different than landmarks and deserve a slot on their own in **artifact**?

The canonical use case for something along the lines of this are twofold:

1. Promotions and events: one would want to anchor assets to landmarks within a specific date range (e.g. only on the fourth of July)
1. Geofencing: one would want to make the distinction between certain areas and display things differently. For example, certain assets apply to cars in dealerships (e.g. comparison charts, reviews) versus on the street (e.g. general information, specifications).

**Comment by skonig-google** [comment]
The second absolutely seems like a composite landmark to me; it's the union
of two landmarks (location and objects).  For the first, I could see two
ways to address this: one, punt.  The web historically hasn't had a great
way to handle temporal/expiring content, requiring explicit publisher
action (e.g. take down page, change page content to reflect fact that the
promotion has expired, etc.); it's not clear that we need to address this
broader challenge just for AR.  If we chose to address it for AR, we could
add 'time' as a restriction, but I feel like this just pushes the problem
elsewhere (e.g., crawlers now have to purge items from their index after it
expires).  I would lean towards punt.

**Comment by mpsalisbury** [comment]
I'll argue that Geofencing is not a composite landmark. 

I think the landmark is the thing to which the asset is to be attached. In Sam's example, this is the cars, not the dealership. But the asset is only intended to appear when the car is near the dealership. That would be a restriction.

That said, I'd be fine with punting this as well.

**Comment by samuelgoto** [comment]
Our original formulation of ```CompositeLandmark``` isn't holding up very well, and was added without a concrete application that really tested its use. I think the formulation "landmark is the thing to which the asset is attached to" is holding up better and I'd be happy to use that as opposed to ```CompositeLandmark``` (i.e. the clarification of using ```restrictions``` in ```Artifact``` buys us removing the concept of ```CompositeLandmark``` which seems like a simple win). 

Unless anyone opposes, I'll make edits to the original proposal to make that clarification point.

**Comment by skonig-google** [comment]
I think a single landmark + restrictions is fine.

**Comment by samuelgoto** [comment]
Done. Closing.

Feel free to take a look at the diff and lmk if I missed something or could make anything clearer. As I add more examples/tests/implementation, I'm sure we'll find bugs, but this should serve as a starting point.

https://github.com/samuelgoto/arpub/commit/8cc01a7e57c3c98f05341adffda1428abc165993
